### ISSUE TITLE
HowTo integrate Node-RED in an nuxt application

### ISSUE THREAD

**Issue by svenflender** [TotallyInformation/node-red-template-embedded#5]
Hi
can you add an example how to embedd node-red into a nuxt application.
Want to build an dashboard application with various infomation about a rpi and also integrate node-red as some menu point. I want the menu visible all time and node-red has to be a part of the app.
Also want to integrate node-red console logging and a restart functionality.

can you help me with an simple approach?

thx and best regards.

**Comment by TotallyInformation** [comment]
Hi, thanks for reaching out. However, this repo is rather abandoned now since others have produced more information. 

If you want nuxt integration I would have thought that it would be better for you to use node-red-contrib-uibuilder which is another of my nodes and is in active development. It comes with VueJS integration out of the box.

I don't think you will be able to use nuxt with the Node-RED Dashboard however as that is designed to be used by people with no web development experience using an embedded version of Angular v1 and as such is very limited for further integration.

I created uibuilder for that reason. It takes the opposite approach to Dashboard in that it leaves you free to create anything you want with any (or no) framework.

Can I please suggest that you raise a new thread in the Node-RED forum? There may well be other people who have already used nuxt with Node-RED, I'm afraid that I haven't.

Certainly I am interested to see anyone using nuxt with uibuilder and would happily take a new WIKI article from anyone who has set it up.

https://discourse.nodered.org/
